# -*- coding: utf-8 -*-
"""Movie_Recommendation_List.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15-49ljKkikm9b8T3-TWkxAi9YhNY52x1
"""

# Movie Recommendation System

#Import Library

import pandas as pd

import numpy as np

#import Data

first=pd.read_csv("https://raw.githubusercontent.com/YBI-Foundation/Dataset/main/Movies%20Recommendation.csv")

first.head()

first.info

# Describe Data

first.describe()

first.columns

first_features=first[['Movie_Genre','Movie_Keywords','Movie_Tagline','Movie_Cast','Movie_Director']].fillna('')

first_features.shape

first_features

A=first_features['Movie_Genre']+''+first_features['Movie_Keywords']+''+first_features['Movie_Tagline']+''+first_features['Movie_Cast']+''+first_features['Movie_Director']+''

A

A.shape

from sklearn.feature_extraction.text import TfidfVectorizer

Tfidf= TfidfVectorizer()

A=Tfidf.fit_transform(A)

A.shape

print(A)

from sklearn.metrics.pairwise import cosine_similarity

similarity_score=cosine_similarity(A)

similarity_score

similarity_score.shape

Favourite_Movie_Name=input('Enter the Name :')

print(Favourite_Movie_Name)

All_Movies_Title_List=first['Movie_Title'].tolist()

import difflib

Movie_Recommendation=difflib.get_close_matches(Favourite_Movie_Name,All_Movies_Title_List)
print(Movie_Recommendation)

Close_Match=Movie_Recommendation[0]
print(Close_Match)

Index_of_Close_Match_Movie=first[first.Movie_Title == Close_Match]['Movie_ID'].values[0]
print(Index_of_Close_Match_Movie)

Recommendation_Score=list(enumerate(similarity_score[Index_of_Close_Match_Movie]))
print(Recommendation_Score)

len(Recommendation_Score)

Sorted_Similar_Movies= sorted(Recommendation_Score,key=lambda x:x[1],reverse=True)
print(Sorted_Similar_Movies)

print('Top Movies Suggested for you : \n')
i=1
for movie in Sorted_Similar_Movies:
  index = movie[0]
  title_from_index=first[first.index==index]['Movie_Title'].values[0]
  if(i<31):
    print(i,'.',title_from_index)
    i+=1